name: CI

on: [push, workflow_dispatch]

jobs:
  generate-epub:
    name: Create ePub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create ePub
        uses: harrymaynard/markdowntoepub-action@main
        with:
          markdownFiles: |-
            test-data/publication.md
            test-data/chapter-*.md
          title: My Book
          author: John Doe
          publisher: ACME Publishing Inc.
          cover: test-data/images/cover.jpg
          version: 3
          lang: en
          tocTitle: My Table of Contents
          hideToC: false
          output: my-book.epub
