name: Upload Release Asset

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create ePub
        uses: harrymaynard/markdown-to-epub-action@main
        with:
          markdownFiles: |-
            test-data/publication.md
            test-data/chapter-*.md
          title: My Book
          author: John Doe
          publisher: ACME Publishing Inc.
          cover: test-data/images/cover.jpg
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: book.epub
          asset_name: book.epub
          asset_content_type: application/epub+zip
